Fix Windows builds
This fixes the following error:

error[E0433]: failed to resolve: could not find `fs` in `windows`
   --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\async-tar-0.4.2\src\entry.rs:588:41
    |
588 |                 async_std::os::windows::fs::symlink_file(src, dst).await
    |                                         ^^ could not find `fs` in `windows`

Which is because `fs` is unstable in Windows:
https://docs.rs/async-std/1.11.0/async_std/os/windows/fs/index.html