CI: Fix udeps (#763)
This fixes the following error from CI:

```
error: the option `Z` is only accepted on the nightly compiler

note: selecting a toolchain with `+toolchain` arguments require a rustup proxy; see <https://rust-lang.github.io/rustup/concepts/index.html>

help: consider switching to a nightly toolchain: `rustup default nightly`

note: for more information about Rust's stability policy, see <https://doc.rust-lang.org/book/appendix-07-nightly-rust.html#unstable-features>

error: could not compile `sharded-slab` (lib)
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.
```

Relates to https://github.com/est31/cargo-udeps/issues/104 (one needs to
pass +nightly to `cargo` so that correct / necessary rustc is used).