Fix crash when dragging to the edge of the screen
Previously, when dragging near the edge of the window, the game would sometimes crash with the below trace, seemingly due to a small rounding error of around a pixel.

Crash message: thread 'Compute Task Pool (3)' panicked at 'Top right corner is not within screen range: Vec2(-0.22984987, 1.0011313)', crates/core/src/screengeom.rs:49:13

This change simply clamps the mouse position to within the screen bounds in order to avoid this error.