Solve clippy::forget-non-drop lint error
We started to get a Clippy error in CI:

error: call to `std::mem::forget` with a value that does not implement `Drop`. Forgetting such a type is the same as dropping it
  --> crates/spawner/src/spawner.rs:19:10
   |
19 | #[derive(Bundle)]
   |          ^^^^^^
   |
   = note: `-D clippy::forget-non-drop` implied by `-D warnings`
note: argument has type `spawner::Spawn`
  --> crates/spawner/src/spawner.rs:19:10
   |
19 | #[derive(Bundle)]
   |          ^^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#forget_non_drop
   = note: this error originates in the derive macro `Bundle` (in Nightly builds, run with -Z macro-backtrace for more info)

The failing lint was recently added in
https://github.com/rust-lang/rust-clippy/pull/8630. Unfortunately, it is
not possible to disable linting of code generated by external macros
https://github.com/rust-lang/rust-clippy/issues/407.

The issues on Bevy site is tracked here
https://github.com/bevyengine/bevy/issues/4601